### ISSUE TITLE
404 for basic request

### ISSUE THREAD

**Issue by rossdrew** [bkielczewski/example-spring-mvc-initializer#9]
Cloned this and ran it ('mvn jetty:Run') on jdk1.7.0_75 and no pages are served from localist:8080, just your plain old "Whitelabel Error Page" complaining about a 404

**Comment by bkielczewski** [comment]
Thanks for checking it out. Are you on Mac? Change this in `pom.xml`:

```
<host>localhost</host>
```

to:

```
<host>127.0.0.1</host>
```

And then do http://127.0.0.1/

Closing, this is not an issue with the code.

**Comment by rossdrew** [comment]
Arg! Thanks.  I hate Mac!
